# https://github.com/vookimedlo/antlr-swift-framework/

language: swift
xcode_project: Antlr4.xcodeproj
xcode_destination: platform=macOS

os: osx
osx_image: xcode11

sudo: false

compiler:
  - clang

before_script:
  - 'uname -a'

script:
  - 'xcodebuild -target Antlr4'
  - 'xcodebuild -scheme Antlr4-Package test'

after_script:
  - 'echo "Done."'
